// Security response headers for install.kaeva.app.
//
// WHY THIS LIVES OUTSIDE functions/: Cloudflare Pages routes EVERY file under
// functions/ as a public endpoint, so a shared helper placed there would also
// become a URL (the same constraint that forced LAST_KNOWN_GOOD to be inlined
// in functions/api/desktop.js). Only functions/ is route-mapped; Pages bundles
// imports from anywhere else in the repo, so lib/ is shared code and nothing
// more. Verified with `wrangler pages functions build`, which resolves this
// import into the bundle without minting a route for it.
//
// WHY NOT _headers: Cloudflare is explicit that "custom headers defined in the
// _headers file are not applied to responses generated by Pages Functions"
// (developers.cloudflare.com/pages/configuration/headers/). On this project `/`
// IS a Function — functions/index.js does the curl-vs-browser content
// negotiation — so a _headers rule for `/` would silently do nothing. The
// landing page and every /api/* response can only be hardened from code. A
// _headers file still ships alongside this, for the paths that really are
// served as static assets.
//
// MEASURED BEFORE (2026-08-20, install.kaeva.app): the landing page and all
// four API endpoints returned NO Content-Security-Policy, NO
// X-Content-Type-Options, NO X-Frame-Options, NO Referrer-Policy and NO
// Strict-Transport-Security. The sibling surface app.kaeva.app has carried the
// full set for a while; HSTS there is scoped to app.kaeva.app and its
// subdomains, so it never covered this host.

/**
 * Applied to every response this project emits.
 *
 * Strict-Transport-Security is the ONE header here with a client-side
 * commitment: a browser that sees it will refuse plaintext to this host for a
 * year. It is deliberately sent WITHOUT `preload`, so winding it down only
 * requires serving `max-age=0` and does not involve asking a browser vendor to
 * delist the domain. The value matches app.kaeva.app so the two surfaces agree.
 */
export const BASE_SECURITY_HEADERS = Object.freeze({
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'geolocation=(), camera=(), microphone=(), payment=(), usb=()',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
});

/**
 * Document CSP, derived from what landing.html actually uses rather than copied
 * from another project:
 *   - one inline <script> and two inline <style> blocks, no external JS or CSS,
 *     hence 'unsafe-inline' on those two directives and nothing wider. There is
 *     no eval, so 'unsafe-eval' is deliberately absent.
 *   - the only fetch is `fetch('/api/desktop')` -> connect-src 'self'.
 *   - the waitlist <form> posts to /api/waitlist -> form-action 'self'.
 *   - no <img>, no webfonts, no third-party origins.
 * Outbound links (app.kaeva.app, github.com, and the release-asset URLs the
 * download list writes into anchor hrefs) are top-level navigations, which no
 * fetch directive governs, so they keep working under this policy.
 */
export const DOCUMENT_CSP = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "object-src 'none'",
].join('; ');

/**
 * Merge the security headers into a plain header bag, without clobbering
 * anything the caller set on purpose (Content-Type, Cache-Control, X-Served-By,
 * X-Desktop-Resolved, ...).
 *
 * @param {Record<string,string>} [headers] caller's headers; not mutated
 * @param {{ document?: boolean }} [opts] `document: true` also attaches the CSP
 * @returns {Record<string,string>}
 */
export function withSecurityHeaders(headers, opts) {
  const out = { ...(headers || {}) };
  for (const [k, v] of Object.entries(BASE_SECURITY_HEADERS)) out[k] = v;
  if (opts && opts.document) out['Content-Security-Policy'] = DOCUMENT_CSP;
  return out;
}

/**
 * Re-wrap an existing Response with the security headers layered on.
 *
 * Used for the asset passthrough in functions/index.js: env.ASSETS.fetch()
 * returns a Response whose headers we must preserve (Content-Type, ETag,
 * Cache-Control) while still adding ours. Streams the body — never buffers it,
 * so a large installer script is not read into memory to add a header.
 *
 * @param {Response} res
 * @param {{ document?: boolean }} [opts]
 * @returns {Response}
 */
export function secureResponse(res, opts) {
  const headers = new Headers(res.headers);
  for (const [k, v] of Object.entries(BASE_SECURITY_HEADERS)) headers.set(k, v);
  if (opts && opts.document) headers.set('Content-Security-Policy', DOCUMENT_CSP);
  return new Response(res.body, { status: res.status, statusText: res.statusText, headers });
}
